name: Build and Deploy
on:
  pull_request:
    types: [opened, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install dependencies
        run: |
          npm run ci
      - name: Build
        run: |
          npm run build
      - name: Run tests
        run: |
          npm run start:ci